apiVersion: v1
kind: Pod
metadata:
  name: busybox-load
spec:
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'while true; do wget -q -O- http://react-app-service.default.svc.cluster.local; done']
